# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {D:/23221111/Data S2/Semester 2/System on Chip/Project/tugas2/tugas2.cache/wt} [current_project]
set_property parent.project_path {D:/23221111/Data S2/Semester 2/System on Chip/Project/tugas2/tugas2.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {d:/23221111/Data S2/Semester 2/System on Chip/Project/tugas2/tugas2.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  {D:/23221111/Data S2/Semester 2/System on Chip/Project/tugas2/tugas2.srcs/sources_1/new/half_adder.v}
  {D:/23221111/Data S2/Semester 2/System on Chip/Project/tugas2/tugas2.srcs/sources_1/new/dff.v}
  {D:/23221111/Data S2/Semester 2/System on Chip/Project/tugas2/tugas2.srcs/sources_1/new/full_adder.v}
  {D:/23221111/Data S2/Semester 2/System on Chip/Project/tugas2/tugas2.srcs/sources_1/new/top.v}
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc {{D:/23221111/Data S2/Semester 2/System on Chip/Project/tugas2/tugas2.srcs/constrs_1/new/sys_clk_l16.xdc}}
set_property used_in_implementation false [get_files {{D:/23221111/Data S2/Semester 2/System on Chip/Project/tugas2/tugas2.srcs/constrs_1/new/sys_clk_l16.xdc}}]


synth_design -top top -part xc7z010clg400-1


write_checkpoint -force -noxdef top.dcp

catch { report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb }
